### ISSUE TITLE
Replication on mini-ImageNet

### ISSUE THREAD

**Issue by hwidong-na** [indy-lab/ProtoTransfer#1]
Hi,

Thanks for uploading great work. It is really exiting to hear your self-supervised learning outperforms MAML on mini-ImageNet! 

I'm trying to replicate your results in the paper. Following the [instruction](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini#for-evaluation), however, I got slightly degraded accuracy.

For 1-shot, 
```
$ python prototransfer/eval.py --dataset miniimagenet --eval_ways 5 --eval_support_shots 1 --eval_query_shots 15 --sup_finetune --ft_freeze_backbone --load_path prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar' (epoch 1489)
Evaluating prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar...
Test loss 4.5765 and accuracy 44.41 +- 0.77
```

For 5-shot, 
```
$ python prototransfer/eval.py --dataset miniimagenet --eval_ways 5 --eval_support_shots 5 --eval_que
ry_shots 15 --sup_finetune --ft_freeze_backbone --load_path prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar' (epoch 1489)
Evaluating prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs.pth.tar...
Test loss 1.5548 and accuracy 61.38 +- 0.74
```

Is it suppose to be similar to the last row in Table 3. (Testing ProtoTune w/ FT)?

The training stops  at epoch 1689, seems a bit early. 
```
$ python prototransfer/train.py --dataset miniimagenet   --train_support_shots 1   --train_query_shots 3      --no_aug_support                                                                                                                                  Used device: cuda
Save path is: prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs
Early stopping with patience 200 epochs
Setting:
Namespace(backbone='conv4', batch_size=50, datapath='../few_data/', dataset='miniimagenet', distance='euclidean', epochs=10000, iterations=100, learn_temperature=False, load_best=False, load_last=False, load_path='', lr=0.001, lr_decay_rate=0.5, lr_decay_step=25000, merge_train_val=False, n_classes=None, n_images=None, no_aug_query=False, no_aug_support=True, num_data_workers_cpu=0, num_data_workers_cuda=8, patience=200, save=True, save_path='', self_sup_loss='proto', train_query_shots=3, train_support_shots=1)

Training ...
Epoch 1690, loss 0.0877, accuracy 0.9701:  17%|██████████▋                                                    | 1689/10000 [2:56:48<14:30:17,  6.28s/epochs]
Early stopping at epoch 1689, because there was no                      improvement for 200 epochs
Epoch 1690, loss 0.0877, accuracy 0.9701:  17%|██████████▋                                                    | 1689/10000 [2:56:48<14:30:03,  6.28s/epochs]
-------------- Best validation loss 0.0756 with accuracy 0.9760
```

Any suggestions?

Best regards,
Hwidong Na

**Comment by ArnoutDevos** [comment]
Hi Hwidong,

Thanks for checking out our code & paper!

I see that you are using the ProtoNet pre-trained network `.../proto_mini...`, and advise to instead use the ProtoCLR pre-trained network `.../protoclr_mini...` for evaluation of ProtoTransfer (=ProtoCLR + ProtoTune).

I (re-)ran the exact command from the [instructions](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini#for-evaluation) I get results matching those from the [ProtoTransfer paper](https://arxiv.org/abs/2006.11325) (see table below). Selecting the correct checkpoint is important.

### Commands
mini-ImageNet 5-way 1-shot
```
python prototransfer/eval.py --dataset miniimagenet --eval_ways 5 --eval_support_shots 1 --eval_query_shots 15 --sup_finetune --ft_freeze_backbone --load_path prototransfer/checkpoints/protoclr/protoclr_miniimagenet_conv4_euclidean_1supp_3query_50bs_best.pth.tar
```

mini-ImageNet 5-way 5-shot
```
python prototransfer/eval.py --dataset miniimagenet --eval_ways 5 --eval_support_shots 5 --eval_query_shots 15 --sup_finetune --ft_freeze_backbone --load_path prototransfer/checkpoints/protoclr/protoclr_miniimagenet_conv4_euclidean_1supp_3query_50bs_best.pth.tar
```

### Results

|    mini-ImageNet       | 5-way 1-shot | 5-way 5-shot |
|-----------|--------------|--------------|
| [this code]() | 45.22 ± 0.77 | 63.19 ± 0.68 |
| [ProtoTransfer paper](https://arxiv.org/abs/2006.11325)     | 45.67 ± 0.79 | 62.99 ± 0.75 |

Let me know if this solves the problem?

**Comment by hwidong-na** [comment]
Hi Arnout,

Thank you for your prompt reply!

I used same training command in [expertiments/protoclr_miniimagenet.sh](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/experiments/protoclr_miniimagenet.sh). I suppose that the name of the model I trained is `proto`  because of the default `self_sup_loss` value. I ran the training phase multiple times but did not get any model matching the scores from the paper.

Yes, the accuracy using the pre-trained [model](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/prototransfer/checkpoints/protoclr/protoclr_miniimagenet_conv4_euclidean_1supp_3query_50bs_best.pth.tar) results similar scores. Fine-tune options during the evaluation phase looks same as I used (`--sup_finetune --ft_freeze_backbone`, right?)

I'll post the results from the other training settings soon.

Best,
Hwidong

**Comment by ArnoutDevos** [comment]
> I used same training command in [expertiments/protoclr_miniimagenet.sh](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/experiments/protoclr_miniimagenet.sh). I suppose that the name of the model I trained is `proto`  because of the default `self_sup_loss` value. I ran the training phase multiple times but did not get any model matching the scores from the paper.

- As you mention, using [expertiments/protoclr_miniimagenet.sh](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/experiments/protoclr_miniimagenet.sh) should work. I am running this again.
- You are right that the model will be called "`proto_...`". Sorry for this name inconsistency.

> Yes, the accuracy using the pre-trained model results similar scores. Fine-tune options during the evaluation phase looks same as I used (--sup_finetune --ft_freeze_backbone, right?)

Great to hear that the results match :100: ! The finetuning flags are the same indeed.

**Comment by ArnoutDevos** [comment]
I trained from scratch again, evaluated on the pre-trained model as well, and get the following (satisfactory) results:

|    mini-ImageNet       | 5-way 1-shot | 5-way 5-shot |5-way 20-shot |5-way 50-shot |
|-----------|--------------|--------------|--------------|--------------|
| This repo, [trained from scratch](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini#for-training) + [evaluation](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini#for-evaluation)| 45.19 ± 0.81 | 61.97 ± 0.73 | 72.05 ± 0.58 | 76.77 ± 0.52 |
| This repo, [pre-trained model file](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/prototransfer/checkpoints/protoclr/protoclr_miniimagenet_conv4_euclidean_1supp_3query_50bs_best.pth.tar) + [evaluation](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini#for-evaluation) | 45.22 ± 0.77 | 63.19 ± 0.68 | 72.99 ± 0.59  | 76.92 ± 0.52 |
| [ProtoTransfer paper](https://arxiv.org/abs/2006.11325)     | 45.67 ± 0.79 | 62.99 ± 0.75 | 72.34 ± 0.58 | 77.22 ± 0.52 |

Unless there are concerns/questions, I will close this issue.

**Comment by hwidong-na** [comment]
I also [trained from scratch](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/experiments/protoclr_cub.sh) using CUB-200, [evaluated](https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/experiments/eval_protoclr_cub2mini.sh) on mini-ImageNet, and get the following results:

CUB2mini-Imagenet  | 5-way 1-shot | 5-way 5-shot | 5-way 20-shot | 5-way 50-shot
-- | -- | -- | -- | --
ProtoCLR + ProtoNet (this repo, run1)  | 34.68 ± 0.68 |  52.08 ± 0.65 |  61.72 ± 0.62 | **63.76 ± 0.60**
ProtoCLR + ProtoNet (this repo, run2)  | 35.41 ± 0.66 |  52.16 ± 0.67 |  61.38 ± 0.58 | **64.40 ± 0.59**
ProtoCLR + ProtoNet [paper](https://arxiv.org/abs/2006.11325) | 34.56 ± 0.61 |  52.76 ± 0.63 | 62.76 ± 0.59 | 66.01 ± 0.55
ProtoCLR + ProtoTune (this repo, run1) | 34.30 ± 0.61  |  **50.89 ± 0.67** |  62.74 ± 0.62  |  68.60 ± 0.58
ProtoCLR + ProtoTune (this repo, run2) | 35.08 ± 0.64  |  **50.54 ± 0.70** |  62.30 ± 0.64  |  68.13 ± 0.58
ProtoCLR + ProtoTune [paper](https://arxiv.org/abs/2006.11325) | 35.37 ± 0.63 | 52.38 ± 0.66 | 63.82 ± 0.59 | 68.95 ± 0.57

I think some of differences to the paper are not negligible, especially for figures in bold.

Also, the average values differ from one runs to the other. Is that expected or am I doing something wrong?

Here are the training and evaluation logs.

Training
```
$ bash experiments/protoclr_miniimagenet.sh
++++++++++++++++++++++++++++++++++++++++++++++++
+++++      ProtoCLR: Miniimagenet            +++++
++++++++++++++++++++++++++++++++++++++++++++++++
Used device: cuda
Save path is: prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs
Early stopping with patience 200 epochs
Setting:
Namespace(backbone='conv4', batch_size=50, datapath='../few_data/', dataset='miniimagenet', distance='euclidean', epochs=10000, iterations=100, learn_temperature=False, load_best=False, load_last=False, load_path='', lr=0.001, lr_decay_rate=0.5, lr_decay_step=25000, merge_train_val=False, n_classes=None, n_images=None, no_aug_query=False, no_aug_support=True, num_data_workers_cpu=0, num_data_workers_cuda=8, patience=200, save=True, save_path='', self_sup_loss='proto' , train_query_shots=3, train_support_shots=1)

Training ...
Epoch 1974, loss 0.0734, accuracy 0.9751:  20%|████████████▋                                                   | 1973/10000 [2:50:37<11:39:55,  5.23s/epochs]
Early stopping at epoch 1973, because there was no                      improvement for 200 epochs
Epoch 1974, loss 0.0734, accuracy 0.9751:  20%|████████████▋                                                   | 1973/10000 [2:50:37<11:34:09,  5.19s/epochs]
-------------- Best validation loss 0.0714 with accuracy 0.9765
```

Evaluation
```
$ bash experiments/eval_protoclr_cub2mini.sh
++++++++++++++++++++++++++++++++++++++++++++++++
+++++ Eval ProtoCLR: CUB2mini-Imagenet     +++++
++++++++++++++++++++++++++++++++++++++++++++++++
ProtoCLR
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 6.7516 and accuracy 34.68 +- 0.65
This was: ProtoCLR 1 shot
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 1.9980 and accuracy 52.08 +- 0.65
This was: ProtoCLR 5 shot
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 1.2684 and accuracy 61.72 +- 0.62
This was: ProtoCLR 20 shot
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 1.1332 and accuracy 63.76 +- 0.60
This was: ProtoCLR 50 shot
ProtoTransfer
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 6.6139 and accuracy 34.30 +- 0.61
This was: ProtoTrasnfer 1 shot
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 2.0546 and accuracy 50.89 +- 0.67
This was: ProtoTrasnfer 5 shot
Used device: cuda
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 1.1370 and accuracy 62.30 +- 0.64
Supervised data loader for miniimagenet:test.
Loaded checkpoint 'prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar' (epoch 1040)
Evaluating prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar...
Test loss 0.8811 and accuracy 68.13 +- 0.58
This was: ProtoTrasnfer 50 shot
```

**Comment by carmete** [comment]
Hi Hwidong

Thank you for exploring our code!

Your training log states that you trained on mini-imageNet:
```
bash experiments/protoclr_miniimagenet.sh
...
Save path is: prototransfer/checkpoints/proto_miniimagenet_conv4_euclidean_1supp_3query_50bs
```

I guess you were running the correct `bash experiments/protoclr_cub.sh` instead? The evaluation looks fine. Only the "best" epoch (1040), selected via early stopping during training, seems a bit low (see below). 

Further to your questions:

> The training stops at epoch 1689, seems a bit early.

This is within the range of last epochs we also observed during training. For example, the pre-trained CUB-200 checkpoint `omni-mini/prototransfer/checkpoints/protoclr/proto_cub_conv4_euclidean_1supp_3query_50bs_best.pth.tar` shows

'Validation loss 0.05796 and accuracy 0.982 in epoch 1658' as its best epoch.

Such output can be obtained through the little helper script `omni-mini/prototransfer/checkpoints/inspect_checkpoint.py`. It will also print the exact training setup used.

> Also, the average values differ from one runs to the other. Is that expected or am I doing something wrong?

It's expected. At least in the range of variations between your runs 1 and 2. 

With respect to the bold figures, we will have to investigate. You are right that the differences seem a bit too big. I presume you are using the exact same setup as described in this repo? Which installation method did you use?

**Comment by hwidong-na** [comment]
> I guess you were running the correct bash experiments/protoclr_cub.sh instead? The evaluation looks fine. Only the "best" epoch (1040), selected via early stopping during training, seems a bit low (see below).

You are right. Below is the training log for the CUB-200.

```
$ bash experiments/protoclr_cub.sh
++++++++++++++++++++++++++++++++++++++++++++++++
+++++      ProtoCLR: CUB                   +++++
++++++++++++++++++++++++++++++++++++++++++++++++
Used device: cuda
Save path is: prototransfer/checkpoints/proto_cub_conv4_euclidean_1supp_3query_50bs
Early stopping with patience 200 epochs
Setting:
Namespace(backbone='conv4', batch_size=50, datapath='../few_data/', dataset='cub', distance='euclidean', epochs=10000, iterations=100, learn_temperature=Fals
e, load_best=False, load_last=False, load_path='', lr=0.001, lr_decay_rate=0.5, lr_decay_step=25000, merge_train_val=False, n_classes=None, n_images=None, no
_aug_query=False, no_aug_support=True, num_data_workers_cpu=0, num_data_workers_cuda=8, patience=200, save=True, save_path='', self_sup_loss='proto', train_q
uery_shots=3, train_support_shots=1)

Training ...
Epoch 1241, loss 0.0637, accuracy 0.9795:  12%|███████▉                                                        | 1240/10000 [5:33:59<39:12:28, 16.11s/epochs]
Early stopping at epoch 1240, because there was no                      improvement for 200 epochs
Epoch 1241, loss 0.0637, accuracy 0.9795:  12%|███████▉                                                        | 1240/10000 [5:33:59<39:19:28, 16.16s/epochs]
-------------- Best validation loss 0.0596 with accuracy 0.9796
```

> It's expected. At least in the range of variations between your runs 1 and 2.

Thank you for clarifying that.

> With respect to the bold figures, we will have to investigate. You are right that the differences seem a bit too big. I presume you are using the exact same setup as described in this repo? Which installation method did you use?

I followed the [setup via conda](https://github.com/indy-lab/ProtoTransfer/tree/master/omni-mini/setup#via-conda).

Best,
Hwidong

**Comment by carmete** [comment]
Hi Hwidong!

I extended your CUB --> mini-ImageNet table with my own results:

| Train                    | Eval      | Epoch | Setup  | 1-shot        |     5-shot    |    20-shot    |    50-shot    |
|--------------------------|-----------|-------|--------|---------------|:-------------:|:-------------:|:-------------:|
| Pre-trained ProtoCLR     | ProtoNet  | 1658  | Pip    | 34.98 +- 0.65 | 53.03 +- 0.66 | 62.51 +- 0.59 | 65.50 +- 0.58 |
| Pre-trained ProtoCLR     | ProtoNet  | 1658  | Docker | 34.91 +- 0.63 | 52.66 +- 0.63 | 62.95 +- 0.62 | 65.36 +- 0.57 |
| From scratch ProtoCLR    | ProtoNet  | 1505  | Docker | 35.29 +- 0.65 | 53.06 +- 0.68 | 62.25 +- 0.62 | 65.04 +- 0.59 |
| Hwidong's ProtoCLR Run 1 | ProtoNet  | 1040  | Conda  | 34.68 ± 0.68  | 52.08 ± 0.65  | 61.72 ± 0.62  | 63.76 ± 0.60  |
| Paper's ProtoCLR         | ProtoNet  | 1658  | Docker | 34.56 ± 0.61  | 52.76 ± 0.63  | 62.76 ± 0.59  | 66.01 ± 0.55  |
| Pre-trained ProtoCLR     | ProtoTune | 1658  | Docker | 35.49 +- 0.64 | 52.52 +- 0.66 | 63.59 +- 0.61 | 69.48 +- 0.52 |
| From scratch ProtoCLR    | ProtoTune | 1505  | Docker | 36.13 +- 0.67 | 52.11 +- 0.71 | 63.11 +- 0.64 | 69.30 +- 0.56 |
| Hwidong's ProtoCLR Run 1 | ProtoTune | 1040  | Conda  | 34.30 ± 0.61  | 50.89 ± 0.67  | 62.74 ± 0.62  | 68.60 ± 0.58  |
| Paper's ProtoCLR         | ProtoTune | 1658  | Docker | 35.37 ± 0.63  | 52.38 ± 0.66  | 63.82 ± 0.59  | 68.95 ± 0.57  |

My own reproductions seem to match the reported results quite well (exceeding them sometimes). I re-evaluated on the checkpoint used in the paper and re-trained from scratch.

> I followed the setup via conda

It was faster for me to train/eval on Docker/Pip setup, but it might be good to re-run with Conda as well.

I'm not sure, where your differences are coming from. Maybe it's really just that training stopped very early (epoch 1040). Or it might be the Conda setup. I would have to do more runs to get definite results.

Here is my own train/eval log:
[CUB2mini_log.txt](https://github.com/indy-lab/ProtoTransfer/files/4920140/CUB2mini_log.txt)
