### ISSUE TITLE
Some requests for visualization of the results

### ISSUE THREAD

**Issue by CSer-Tang-hao** [indy-lab/ProtoTransfer#2]
This is an encouraging work and gives me some inspirations. To better understand some observations in this paper, can you provide t-SNE codes for the visualization of your result?

Looking forward to your reply!

**Comment by ArnoutDevos** [comment]
We're happy that you find our work useful!

We've added the t-SNE notebooks used here:  
https://github.com/indy-lab/ProtoTransfer/blob/master/omni-mini/plots/tsne_plots.ipynb
